/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Ifqxr2MqHku
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Rubik } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Calendar } from "@/components/ui/calendar"
import { Nav } from "@/components/nav"
import { Footer } from "@/components/footer"
import Link from "next/link"

export function Date() {
  return (
    <>
    <div className="flex h-16 items-center justify-between px-6 border-b border-brown-200 dark:border-brown-700 bg-white dark:bg-brown-900">
      <Nav />
    </div>
    <div className="w-full min-h-screen bg-gradient-to-b from-[#8B4513]/20 to-[#D2B48C]/20 py-12 sm:py-16 md:py-20 lg:py-24">
      <div className="text-center">
        <h1 className="text-4xl font-extrabold tracking-tight text-gray-900 dark:text-gray-100 sm:text-5xl lg:text-6xl">
          Book Your Hair Appointment
        </h1>
        <p className="mt-3 max-w-md mx-auto text-base text-gray-500 dark:text-gray-400 sm:text-lg md:mt-5 md:text-xl lg:max-w-3xl">
          Select an available day to schedule your next hair appointment.
        </p>
      </div>
      <div className="mt-10 sm:mt-12 flex justify-center">
        <Calendar
          className="mx-auto max-w-md rounded-lg border border-gray-200 dark:border-gray-700 p-4 sm:p-6 dark:border-gray-800"
          initialFocus
          mode="single"
        />
      </div>
    </div>
    <Footer/>
    </>
  )
}
